#!/bin/bash
apt-get update

apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

apt-get update

apt-get install docker-ce -y

docker volume create portainer_data
docker run -d -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer

#Recursively Remove .DS_Store:
find . -name '.DS_Store' -type f -delete

#Docker images build:
for path in $(ls | grep 'uisg');
do
echo $path" is building";
docker build -t $path -f $path/Dockerfile $path
done
